# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a02828a88c638c7b71e019849ae886c5263b111470c135ff7ccc073591eff2613a7f3364d4d38a9452358b96bbca0964fbd1a35c8b6ae6e46fbf612c24420d5

test:
  secret_key_base: 7a8b7c8bee2444528a75e28af57f492cd144697cb880bbb29e35aa56bfd91d822be778e4a83b8834e0cc2696713a0b5956ce346699f8aaa5e69d5ff89c5287b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
